#!/usr/bin/env python
"""Generate the offline fixtures the workflow's ``-profile test`` needs.

Writes a synthetic GEO series matrix and platform annotation into a cache, plus
a cohort spec pointing at them. The point is a run that exercises every process
in the DAG in about a minute, with no network and no credentials, so that
`nextflow run workflow/main.nf -profile test` is something CI can do on every
push rather than something a person does occasionally by hand.

The data is synthetic and carries a planted signal, so the survival step
produces a non-degenerate model. It says nothing about any real signature.
"""

from __future__ import annotations

import argparse
import gzip
from pathlib import Path

import numpy as np

from hypoxiapipe.ingest.cache import Cache
from hypoxiapipe.signatures.registry import load_bundled

ACCESSION = "GSE00000"
PLATFORM = "GPL0000"
N_SAMPLES = 140
N_NOISE_GENES = 60


def build_annotation(genes: list[str]) -> str:
    """Return a platform annotation mapping one probe per gene."""
    lines = [f"^PLATFORM = {PLATFORM}", "!platform_table_begin", "ID\tGene symbol"]
    lines += [f"PROBE_{i:04d}\t{gene}" for i, gene in enumerate(genes)]
    lines.append("!platform_table_end")
    return "\n".join(lines)


def build_series_matrix(genes: list[str], seed: int = 42) -> str:
    """Return a synthetic GEO series matrix with a planted survival signal."""
    rng = np.random.default_rng(seed)
    samples = [f"GSM{i:06d}" for i in range(N_SAMPLES)]
    expr = rng.normal(8.0, 1.2, (len(genes), N_SAMPLES))

    # Plant a signal in the first three genes so the Cox step has something to
    # find; without it the fixture run would exercise the code but produce a
    # null model, and a null result cannot distinguish "works" from "broken".
    risk = expr[0] * 0.55 + expr[1] * 0.35 - expr[2] * 0.25
    risk = risk - risk.mean()
    time = np.clip(rng.exponential(scale=np.exp(-risk)) * 22, 1.0, 59.0).round(2)
    event = (time < 34).astype(int)

    header = [
        f'!Series_platform_id\t"{PLATFORM}"',
        "!Sample_geo_accession\t" + "\t".join(f'"{s}"' for s in samples),
        "!Sample_characteristics_ch1\t"
        + "\t".join(f'"bcr free time: {v}"' for v in time),
        "!Sample_characteristics_ch1\t" + "\t".join(f'"bcr status: {v}"' for v in event),
        "!series_matrix_table_begin",
        "ID_REF\t" + "\t".join(samples),
    ]
    rows = [
        f"PROBE_{i:04d}\t" + "\t".join(f"{v:.4f}" for v in row)
        for i, row in enumerate(expr)
    ]
    print(f"  planted signal: {int(event.sum())} events in {N_SAMPLES} samples")
    return "\n".join([*header, *rows, "!series_matrix_table_end", ""])


def main() -> int:
    """Write the fixture cache and cohort spec."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tests/fixtures/workflow",
        help="Directory to write the fixture cache and spec into.",
    )
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    # Include the real signature's genes so coverage is 100% and the QC report
    # exercises the coverage check properly.
    signature_genes = list(load_bundled("smith20").genes)
    noise = [f"NOISE{i:03d}" for i in range(N_NOISE_GENES)]
    genes = signature_genes + noise

    cache = Cache(args.out / "cache")
    cache.put(
        f"geo/{ACCESSION}_series_matrix.txt.gz",
        gzip.compress(build_series_matrix(genes).encode()),
        url="fixture://series-matrix",
    )
    cache.put(
        f"geo/{PLATFORM}.annot.gz",
        gzip.compress(build_annotation(genes).encode()),
        url="fixture://platform-annotation",
    )

    spec = args.out / "demo_cohort.yaml"
    spec.write_text(
        f"""# Generated by tools/make_test_fixtures.py - do not edit by hand.
# Synthetic data with a planted signal, for exercising the workflow offline.
name: demo_cohort
source: geo
accession: {ACCESSION}
platform: {PLATFORM}
symbol_authority: "2024-07-01"
log2_transform: false

endpoint:
  name: BCR (5-year capped)
  time_column: bcr_free_time
  event_column: bcr_status
  time_unit: months
  cap_months: 60

expect:
  n_samples: {N_SAMPLES}
  min_genes: {len(genes) - 5}
"""
    )
    print(f"  wrote {spec}")
    print(f"  wrote {args.out / 'cache'} ({len(genes)} genes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
